name 'custom_solr'
maintainer 'Trilitheus'
maintainer_email 'trilitheus@gmail.com'
license 'all_rights'
description 'Installs/Configures solr'
long_description 'Installs/Configures solr'
version '0.1.0'

depends 'java'
depends 'monit-ng', '~> 2.3.0'
