name 'custom_solr'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures custom_solr'
long_description 'Installs/Configures custom_solr'
version '0.1.0'
